export const CURRENCY_EXCHANGE_FIELDS = {
    CURRENCY_AMOUNT_1: 'CURRENCY_AMOUNT_1',
    CURRENCY_AMOUNT_2: 'CURRENCY_AMOUNT_2',
    SELECTED_CURRENCY_1: 'SELECTED_CURRENCY_1',
    SELECTED_CURRENCY_2: 'SELECTED_CURRENCY_2',
}